INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Selatan', '11.01', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Tenggara', '11.02', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Timur', '11.03', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Tengah', '11.04', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Barat', '11.05', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Besar', '11.06', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pidie', '11.07', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Utara', '11.08', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Simeulue', '11.09', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Singkil', '11.10', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bireuen', '11.11', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Barat Daya', '11.12', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gayo Lues', '11.13', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Jaya', '11.14', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nagan Raya', '11.15', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Aceh Tamiang', '11.16', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bener Meriah', '11.17', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pidie Jaya', '11.18', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Banda Aceh', '11.71', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Sabang', '11.72', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Lhokseumawe', '11.73', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Langsa', '11.74', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Subulussalam', '11.75', '11');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tapanuli Tengah', '12.01', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tapanuli Utara', '12.02', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tapanuli Selatan', '12.03', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nias', '12.04', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Langkat', '12.05', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Karo', '12.06', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Deli Serdang', '12.07', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Simalungun', '12.08', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Asahan', '12.09', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Labuhanbatu', '12.10', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Dairi', '12.11', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Toba', '12.12', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mandailing Natal', '12.13', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nias Selatan', '12.14', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pakpak Bharat', '12.15', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Humbang Hasundutan', '12.16', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Samosir', '12.17', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Serdang Bedagai', '12.18', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Batu Bara', '12.19', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Padang Lawas Utara', '12.20', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Padang Lawas', '12.21', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Labuhanbatu Selatan', '12.22', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Labuhanbatu Utara', '12.23', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nias Utara', '12.24', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nias Barat', '12.25', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Medan', '12.71', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pematangsiantar', '12.72', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Sibolga', '12.73', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tanjungbalai', '12.74', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Binjai', '12.75', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tebing Tinggi', '12.76', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Padangsidimpuan', '12.77', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Gunungsitoli', '12.78', '12');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pesisir Selatan', '13.01', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Solok', '13.02', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sijunjung', '13.03', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tanah Datar', '13.04', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Padang Pariaman', '13.05', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Agam', '13.06', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lima Puluh Kota', '13.07', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pasaman', '13.08', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Mentawai', '13.09', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Dharmasraya', '13.10', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Solok Selatan', '13.11', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pasaman Barat', '13.12', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Padang', '13.71', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Solok', '13.72', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Sawahlunto', '13.73', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Padang Panjang', '13.74', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bukittinggi', '13.75', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Payakumbuh', '13.76', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pariaman', '13.77', '13');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kampar', '14.01', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Indragiri Hulu', '14.02', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bengkalis', '14.03', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Indragiri Hilir', '14.04', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pelalawan', '14.05', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Rokan Hulu', '14.06', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Rokan Hilir', '14.07', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Siak', '14.08', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kuantan Singingi', '14.09', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Meranti', '14.10', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pekanbaru', '14.71', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Dumai', '14.72', '14');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kerinci', '15.01', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Merangin', '15.02', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sarolangun', '15.03', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Batanghari', '15.04', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Muaro Jambi', '15.05', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tanjung Jabung Barat', '15.06', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tanjung Jabung Timur', '15.07', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bungo', '15.08', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tebo', '15.09', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Jambi', '15.71', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Sungai Penuh', '15.72', '15');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ogan Komering Ulu', '16.01', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ogan Komering Ilir', '16.02', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Muara Enim', '16.03', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lahat', '16.04', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Musi Rawas', '16.05', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Musi Banyuasin', '16.06', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banyuasin', '16.07', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ogan Komering Ulu Timur', '16.08', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ogan Komering Ulu Selatan', '16.09', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ogan Ilir', '16.10', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Empat Lawang', '16.11', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Penukal Abab Lematang Ilir', '16.12', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Musi Rawas Utara', '16.13', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Palembang', '16.71', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pagar Alam', '16.72', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Lubuk Linggau', '16.73', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Prabumulih', '16.74', '16');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bengkulu Selatan', '17.01', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Rejang Lebong', '17.02', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bengkulu Utara', '17.03', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kaur', '17.04', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Seluma', '17.05', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mukomuko', '17.06', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lebong', '17.07', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepahiang', '17.08', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bengkulu Tengah', '17.09', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bengkulu', '17.71', '17');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lampung Selatan', '18.01', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lampung Tengah', '18.02', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lampung Utara', '18.03', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lampung Barat', '18.04', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tulang Bawang', '18.05', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tanggamus', '18.06', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lampung Timur', '18.07', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Way Kanan', '18.08', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pesawaran', '18.09', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pringsewu', '18.10', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mesuji', '18.11', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tulang Bawang Barat', '18.12', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pesisir Barat', '18.13', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bandar Lampung', '18.71', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Metro', '18.72', '18');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bangka', '19.01', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Belitung', '19.02', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bangka Selatan', '19.03', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bangka Tengah', '19.04', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bangka Barat', '19.05', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Belitung Timur', '19.06', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pangkal Pinang', '19.71', '19');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bintan', '21.01', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Karimun', '21.02', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Natuna', '21.03', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lingga', '21.04', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Anambas', '21.05', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Batam', '21.71', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tanjung Pinang', '21.72', '21');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Administrasi Kepulauan Seribu', '31.01', '31');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Administrasi Jakarta Pusat', '31.71', '31');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Administrasi Jakarta Utara ', '31.72', '31');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Administrasi Jakarta Barat', '31.73', '31');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Administrasi Jakarta Selatan', '31.74', '31');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Administrasi Jakarta Timur', '31.75', '31');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bogor', '32.01', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sukabumi', '32.02', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Cianjur', '32.03', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bandung', '32.04', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Garut', '32.05', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tasikmalaya', '32.06', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ciamis', '32.07', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kuningan', '32.08', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Cirebon', '32.09', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Majalengka', '32.10', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumedang', '32.11', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Indramayu', '32.12', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Subang', '32.13', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Purwakarta', '32.14', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Karawang', '32.15', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bekasi', '32.16', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bandung Barat', '32.17', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pangandaran', '32.18', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bogor', '32.71', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Sukabumi', '32.72', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bandung', '32.73', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Cirebon', '32.74', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bekasi', '32.75', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Depok', '32.76', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Cimahi', '32.77', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tasikmalaya', '32.78', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Banjar', '32.79', '32');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Cilacap', '33.01', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banyumas', '33.02', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Purbalingga', '33.03', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banjarnegara', '33.04', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kebumen', '33.05', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Purworejo', '33.06', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Wonosobo', '33.07', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Magelang', '33.08', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Boyolali', '33.09', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Klaten', '33.10', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sukoharjo', '33.11', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Wonogiri', '33.12', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Karanganyar', '33.13', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sragen', '33.14', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Grobogan', '33.15', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Blora', '33.16', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Rembang', '33.17', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pati', '33.18', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kudus', '33.19', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jepara', '33.20', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Demak', '33.21', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Semarang', '33.22', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Temanggung', '33.23', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kendal', '33.24', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Batang', '33.25', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pekalongan', '33.26', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pemalang', '33.27', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tegal', '33.28', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Brebes', '33.29', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Magelang', '33.71', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Surakarta', '33.72', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Salatiga', '33.73', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Semarang', '33.74', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pekalongan', '33.75', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tegal', '33.76', '33');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kulon Progo', '34.01', '34');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bantul', '34.02', '34');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gunungkidul', '34.03', '34');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sleman', '34.04', '34');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Yogyakarta', '34.71', '34');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pacitan', '35.01', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ponorogo', '35.02', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Trenggalek', '35.03', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tulungagung', '35.04', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Blitar', '35.05', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kediri', '35.06', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Malang', '35.07', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lumajang', '35.08', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jember', '35.09', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banyuwangi', '35.10', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bondowoso', '35.11', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Situbondo', '35.12', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Probolinggo', '35.13', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pasuruan', '35.14', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sidoarjo', '35.15', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mojokerto', '35.16', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jombang', '35.17', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nganjuk', '35.18', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Madiun', '35.19', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Magetan', '35.20', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ngawi', '35.21', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bojonegoro', '35.22', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tuban', '35.23', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lamongan', '35.24', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gresik', '35.25', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bangkalan', '35.26', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sampang', '35.27', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pamekasan', '35.28', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumenep', '35.29', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Kediri', '35.71', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Blitar', '35.72', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Malang', '35.73', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Probolinggo', '35.74', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pasuruan', '35.75', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Mojokerto', '35.76', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Madiun', '35.77', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Surabaya', '35.78', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Batu', '35.79', '35');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pandeglang', '36.01', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lebak', '36.02', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tangerang', '36.03', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Serang', '36.04', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tangerang', '36.71', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Cilegon', '36.72', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Serang', '36.73', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tangerang Selatan', '36.74', '36');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jembrana', '51.01', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tabanan', '51.02', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Badung', '51.03', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gianyar', '51.04', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Klungkung', '51.05', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bangli', '51.06', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Karangasem', '51.07', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buleleng', '51.08', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Denpasar', '51.71', '51');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lombok Barat', '52.01', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lombok Tengah', '52.02', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lombok Timur', '52.03', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumbawa', '52.04', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Dompu', '52.05', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bima', '52.06', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumbawa Barat', '52.07', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lombok Utara', '52.08', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Mataram', '52.71', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bima', '52.72', '52');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kupang', '53.01', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Kab Timor Tengah Selatan', '53.02', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Timor Tengah Utara', '53.03', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Belu', '53.04', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Alor', '53.05', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Flores Timur', '53.06', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sikka', '53.07', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ende', '53.08', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ngada', '53.09', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Manggarai', '53.10', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumba Timur', '53.11', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumba Barat', '53.12', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lembata', '53.13', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Rote Ndao', '53.14', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Manggarai Barat', '53.15', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nagekeo', '53.16', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumba Tengah', '53.17', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sumba Barat Daya', '53.18', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Manggarai Timur', '53.19', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sabu Raijua', '53.20', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Malaka', '53.21', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Kupang', '53.71', '53');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sambas', '61.01', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mempawah', '61.02', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sanggau', '61.03', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Ketapang', '61.04', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sintang', '61.05', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kapuas Hulu', '61.06', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bengkayang', '61.07', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Landak', '61.08', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sekadau', '61.09', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Melawi', '61.10', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kayong Utara', '61.11', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kubu Raya', '61.12', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Pontianak', '61.71', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Singkawang', '61.72', '61');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kotawaringin Barat', '62.01', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kotawaringin Timur', '62.02', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kapuas', '62.03', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Barito Selatan', '62.04', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Barito Utara', '62.05', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Katingan', '62.06', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Seruyan', '62.07', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sukamara', '62.08', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lamandau', '62.09', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gunung Mas', '62.10', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pulang Pisau', '62.11', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Murung Raya', '62.12', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Barito Timur', '62.13', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Palangkaraya', '62.71', '62');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tanah Laut', '63.01', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kotabaru', '63.02', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banjar', '63.03', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Barito Kuala', '63.04', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tapin', '63.05', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Hulu Sungai Selatan', '63.06', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Hulu Sungai Tengah', '63.07', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Hulu Sungai Utara', '63.08', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tabalong', '63.09', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tanah Bumbu', '63.10', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Balangan', '63.11', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Banjarmasin', '63.71', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Banjarbaru', '63.72', '63');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Paser', '64.01', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kutai Kartanegara', '64.02', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Berau', '64.03', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kutai Barat', '64.07', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kutai Timur', '64.08', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Penajam Paser Utara', '64.09', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mahakam Ulu', '64.11', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Balikpapan', '64.71', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Samarinda', '64.72', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bontang', '64.74', '64');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bulungan', '65.01', '65');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Malinau', '65.02', '65');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nunukan', '65.03', '65');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tana Tidung', '65.04', '65');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tarakan', '65.71', '65');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bolaang Mongondow', '71.01', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Minahasa', '71.02', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Sangihe', '71.03', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Talaud', '71.04', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Minahasa Selatan', '71.05', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Minahasa Utara', '71.06', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Minahasa Tenggara', '71.07', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bolaang Mongondow Utara', '71.08', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kep. Siau Tagulandang Biaro', '71.09', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bolaang Mongondow Timur', '71.10', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bolaang Mongondow Selatan', '71.11', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Manado', '71.71', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bitung', '71.72', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tomohon', '71.73', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Kotamobagu', '71.74', '71');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banggai', '72.01', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Poso', '72.02', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Donggala', '72.03', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Toli-Toli', '72.04', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buol', '72.05', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Morowali', '72.06', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banggai Kepulauan', '72.07', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Parigi Moutong', '72.08', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tojo Una Una', '72.09', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sigi', '72.10', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Banggai Laut', '72.11', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Morowali Utara', '72.12', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Palu', '72.71', '72');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Selayar', '73.01', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bulukumba', '73.02', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bantaeng', '73.03', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jeneponto', '73.04', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Takalar', '73.05', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gowa', '73.06', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sinjai', '73.07', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bone', '73.08', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Maros', '73.09', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pangkajene dan Kepulauan', '73.10', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Barru', '73.11', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Soppeng', '73.12', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Wajo', '73.13', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sidenreng Rappang', '73.14', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pinrang', '73.15', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Enrekang', '73.16', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Luwu', '73.17', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tana Toraja', '73.18', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Luwu Utara', '73.22', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Luwu Timur', '73.24', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Toraja Utara', '73.26', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Makassar', '73.71', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Parepare', '73.72', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Palopo', '73.73', '73');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kolaka', '74.01', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Konawe', '74.02', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Muna', '74.03', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buton', '74.04', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Konawe Selatan', '74.05', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bombana', '74.06', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Wakatobi', '74.07', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kolaka Utara', '74.08', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Konawe Utara', '74.09', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buton Utara', '74.10', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kolaka Timur', '74.11', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Konawe Kepulauan', '74.12', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Muna Barat', '74.13', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buton Tengah', '74.14', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buton Selatan', '74.15', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Kendari', '74.71', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Bau Bau', '74.72', '74');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gorontalo', '75.01', '75');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Boalemo', '75.02', '75');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Bone Bolango', '75.03', '75');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pohuwato', '75.04', '75');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Gorontalo Utara', '75.05', '75');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Gorontalo', '75.71', '75');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pasangkayu', '76.01', '76');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mamuju', '76.02', '76');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mamasa', '76.03', '76');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Polewali Mandar', '76.04', '76');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Majene', '76.05', '76');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mamuju Tengah', '76.06', '76');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Maluku Tengah', '81.01', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Maluku Tenggara', '81.02', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Tanimbar', '81.03', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buru', '81.04', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Seram Bagian Timur', '81.05', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Seram Bagian Barat', '81.06', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Aru', '81.07', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Maluku Barat Daya', '81.08', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Buru Selatan', '81.09', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Ambon', '81.71', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tual', '81.72', '81');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Halmahera Barat', '82.01', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Halmahera Tengah', '82.02', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Halmahera Utara', '82.03', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Halmahera Selatan', '82.04', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Sula', '82.05', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Halmahera Timur', '82.06', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pulau Morotai', '82.07', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pulau Taliabu', '82.08', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Ternate', '82.71', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Tidore Kepulauan', '82.72', '82');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jayapura', '91.03', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kepulauan Yapen', '91.05', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Biak Numfor', '91.06', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sarmi', '91.10', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Keerom', '91.11', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Waropen', '91.15', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Supiori', '91.19', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mamberamo Raya', '91.20', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Jayapura', '91.71', '91');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Manokwari', '92.02', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Fak Fak', '92.03', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Teluk Bintuni', '92.06', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Teluk Wondama', '92.07', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Kaimana', '92.08', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Manokwari Selatan', '92.11', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Pegunungan Arfak', '92.12', '92');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Merauke', '93.01', '93');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Boven Digoel', '93.02', '93');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mappi', '93.03', '93');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Asmat', '93.04', '93');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nabire', '94.01', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Puncak Jaya', '94.02', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Paniai', '94.03', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mimika', '94.04', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Puncak', '94.05', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Dogiyai', '94.06', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Intan Jaya', '94.07', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Deiyai', '94.08', '94');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Jayawijaya', '95.01', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Kab Pegunungan Bintang', '95.02', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Yahukimo', '95.03', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tolikara', '95.04', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Mamberamo Tengah', '95.05', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Yalimo', '95.06', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Lanny Jaya', '95.07', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Nduga', '95.08', '95');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sorong', '96.01', '96');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Sorong Selatan', '96.02', '96');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Raja Ampat', '96.03', '96');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Tambrauw', '96.04', '96');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kabupaten', 'Maybrat', '96.05', '96');
INSERT INTO cities (type, name, code, province_code) VALUES ('Kota', 'Sorong', '96.71', '96');