INSERT INTO provinces (code, name) VALUES ('11','Aceh');
INSERT INTO provinces (code, name) VALUES ('12','Sumatera Utara');
INSERT INTO provinces (code, name) VALUES ('13','Sumatera Barat');
INSERT INTO provinces (code, name) VALUES ('14','Riau');
INSERT INTO provinces (code, name) VALUES ('15','Jambi');
INSERT INTO provinces (code, name) VALUES ('16','Sumatera Selatan');
INSERT INTO provinces (code, name) VALUES ('17','Bengkulu');
INSERT INTO provinces (code, name) VALUES ('18','Lampung');
INSERT INTO provinces (code, name) VALUES ('19','Kepulauan Bangka Belitung');
INSERT INTO provinces (code, name) VALUES ('21','Kepulauan Riau');
INSERT INTO provinces (code, name) VALUES ('31','Daerah Khusus Ibukota Jakarta');
INSERT INTO provinces (code, name) VALUES ('32','Jawa Barat');
INSERT INTO provinces (code, name) VALUES ('33','Jawa Tengah');
INSERT INTO provinces (code, name) VALUES ('34','Daerah Istimewa Yogyakarta');
INSERT INTO provinces (code, name) VALUES ('35','Jawa Timur');
INSERT INTO provinces (code, name) VALUES ('36','Banten');
INSERT INTO provinces (code, name) VALUES ('51','Bali');
INSERT INTO provinces (code, name) VALUES ('52','Nusa Tenggara Barat');
INSERT INTO provinces (code, name) VALUES ('53','Nusa Tenggara Timur');
INSERT INTO provinces (code, name) VALUES ('61','Kalimantan Barat');
INSERT INTO provinces (code, name) VALUES ('62','Kalimantan Tengah');
INSERT INTO provinces (code, name) VALUES ('63','Kalimantan Selatan');
INSERT INTO provinces (code, name) VALUES ('64','Kalimantan Timur');
INSERT INTO provinces (code, name) VALUES ('65','Kalimantan Utara');
INSERT INTO provinces (code, name) VALUES ('71','Sulawesi Utara');
INSERT INTO provinces (code, name) VALUES ('72','Sulawesi Tengah');
INSERT INTO provinces (code, name) VALUES ('73','Sulawesi Selatan');
INSERT INTO provinces (code, name) VALUES ('74','Sulawesi Tenggara');
INSERT INTO provinces (code, name) VALUES ('75','Gorontalo');
INSERT INTO provinces (code, name) VALUES ('76','Sulawesi Barat');
INSERT INTO provinces (code, name) VALUES ('81','Maluku');
INSERT INTO provinces (code, name) VALUES ('82','Maluku Utara');
INSERT INTO provinces (code, name) VALUES ('91','Papua');
INSERT INTO provinces (code, name) VALUES ('92','Papua Barat');
INSERT INTO provinces (code, name) VALUES ('93','Papua Selatan');
INSERT INTO provinces (code, name) VALUES ('94','Papua Tengah');
INSERT INTO provinces (code, name) VALUES ('95','Papua Pegunungan');
INSERT INTO provinces (code, name) VALUES ('96','Papua Barat Daya');